version: "3"

env:
  BUILDKITE_AGENT_TOKEN: ""

tasks:
  build:
    dir: "{{ .image }}"
    cmds:
      - docker build -t ghcr.io/danielfrg/{{.image}} .

  run:
    cmds:
      - docker run -it -e BUILDKITE_AGENT_TOKEN="${BUILDKIT_AGENT_TOKEN}" ghcr.io/danielfrg/{{.image}}
