agents:
  queue: "python"

steps:
  - label: "Example Test"
    agents:
      queue: "python"
    command: echo "Hello!"

  - label: "Test aws cli"
    agents:
      queue: "python"
    command: aws --version

  - label: "Test rye"
    agents:
      queue: "python"
    command: rye --version

  - label: "Rye sync"
    agents:
      queue: "python"
    commands:
      - rye init
      - rye add pandas
      - rye sync
